---
version: '3'

services:
  wgs-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/wgs-pipeline:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - .:/wd
    working_dir: /wd
